externalSecrets:
  vaultPath: alarmify/dev/cloudflared/credentials

cloudflared:
  replica:
    allNodes: false
    count: 2

  tunnelConfig:
    name: "dev"

  ingress:
    - hostname: "ui.jrclabs.xyz"
      service: http://gateway.gateway-system.svc.cluster.local:80
    - service: http_status:404
