externalSecrets:
  vaultPath: alarmify/local/cloudflared/credentials

cloudflared:
  tunnelConfig:
    name: "management"

  ingress:
    - hostname: "zitadel.jrclabs.xyz"
      service: http://gateway.gateway-system.svc.cluster.local:80
      originRequest:
        http2Origin: true
    - hostname: "harbor.jrclabs.xyz"
      service: http://gateway.gateway-system.svc.cluster.local:80
    - hostname: "plane.jrclabs.xyz"
      service: http://gateway.gateway-system.svc.cluster.local:80
    - hostname: "vault.jrclabs.xyz"
      service: http://gateway.gateway-system.svc.cluster.local:80
    - service: http_status:404
