apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: externalsecret
  annotations:
    argocd.argoproj.io/managed: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        annotations:
          external-secrets.io/managed-by: external-secrets
        labels:
          app.kubernetes.io/component: credentials
          app.kubernetes.io/instance: cert-manager
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/part-of: cert-manager
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.cloudflareApiToken.vaultPath }}
        metadataPolicy: None
        property: token
