{{- if .Values.vaultClusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: secretstore
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/managed: "true"
spec:
  provider:
    vault:
      server: {{ .Values.vaultClusterSecretStore.vault.server | quote }}
      path: {{ .Values.vaultClusterSecretStore.vault.path | quote }}
      version: {{ .Values.vaultClusterSecretStore.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vaultClusterSecretStore.tokenSecret.name }}
          key: {{ .Values.vaultClusterSecretStore.tokenSecret.key }}
          namespace: {{ .Values.vaultClusterSecretStore.tokenSecret.namespace }}
  retrySettings:
    maxRetries: {{ .Values.vaultClusterSecretStore.retrySettings.maxRetries }}
    retryInterval: {{ .Values.vaultClusterSecretStore.retrySettings.retryInterval }}
{{- end }}
