gateways:
  internal:
    gatewayClassName: gke-l7-rilb
    addressName: ""
    https:
      enabled: true
      certificateRefs:
        - name: gateway-wildcard-tls
  external:
    gatewayClassName: gke-l7-regional-external-managed
    addressName: ""
    https:
      enabled: true
      certificateRefs:
        - name: gateway-wildcard-tls

certificate:
  enabled: true
  dnsNames:
    - "*.jrclabs.xyz"
    - "jrclabs.xyz"

httpRedirectHosts:
  external:
    - vault.jrclabs.xyz
    - harbor.jrclabs.xyz
    - argocd.jrclabs.xyz
  internal: []

healthCheckPolicies:
  - name: vault-ui
    targetService: local-vault-ui
    namespace: vault
    port: 8200
    requestPath: "/v1/sys/health?standbyok=true"
  - name: harbor-core
    targetService: local-harbor-core
    namespace: harbor
    port: 8080
    requestPath: "/api/v2.0/ping"
