gateways:
  internal:
    gatewayClassName: gke-l7-rilb
    addressName: ""
  external:
    gatewayClassName: gke-l7-regional-external-managed
    addressName: ""
    https:
      enabled: true
      certificateRefs:
        - name: gateway-wildcard-tls

certificate:
  enabled: true
  dnsNames:
    - "*.jrclabs.xyz"
    - "jrclabs.xyz"

httpRedirectHosts:
  - vault.jrclabs.xyz

healthCheckPolicies:
  - name: vault-ui
    targetService: local-vault-ui
    namespace: vault
    port: 8200
    requestPath: "/v1/sys/health?standbyok=true"
