{{- if and .Values.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "vault-backup.fullname" . }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-backup.labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials
    external-secrets.io/component: externalsecret
  annotations:
    argocd.argoproj.io/managed: "true"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecretName | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          {{- include "vault-backup.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.vaultPath | quote }}
        metadataPolicy: None
        property: {{ .Values.externalSecrets.properties.accessKeyId | quote }}
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.vaultPath | quote }}
        metadataPolicy: None
        property: {{ .Values.externalSecrets.properties.secretAccessKey | quote }}
    - secretKey: VAULT_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.vaultPath | quote }}
        metadataPolicy: None
        property: {{ .Values.externalSecrets.properties.vaultToken | quote }}
{{- end }}
