apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlantis.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.atlantis.config.github.token }}
  github-token: {{ .Values.atlantis.config.github.token | b64enc }}
  {{- end }}
  {{- if .Values.atlantis.config.github.webhookSecret }}
  webhook-secret: {{ .Values.atlantis.config.github.webhookSecret | b64enc }}
  {{- end }}
  {{- if .Values.atlantis.config.gitlab.token }}
  gitlab-token: {{ .Values.atlantis.config.gitlab.token | b64enc }}
  {{- end }}
  {{- if .Values.atlantis.config.gitlab.webhookSecret }}
  gitlab-webhook-secret: {{ .Values.atlantis.config.gitlab.webhookSecret | b64enc }}
  {{- end }}
