apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser
  namespace: cloudnative-pg-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres-change-me-in-production
