vmcluster:
  enabled: false

vmalert:
  enabled: false

remoteWriteToken:
  enabled: true

vmagent:
  externalLabels:
    cluster: dev
  remoteWrite:
    url: "http://vminsert.jrclabs.xyz/insert/0/prometheus/api/v1/write"
    auth:
      enabled: true
