vmagent:
  externalLabels:
    cluster: management

remoteWriteToken:
  enabled: true
vmauth:
  enabled: true
vmcluster:
  vminsert:
    externalExposure:
      enabled: true
      hostname: vminsert.jrclabs.xyz
  vmstorage:
    nodeSelector:
      storage: persistent
  vmselect:
    nodeSelector:
      storage: persistent
