{{- if and .Values.nats (default true .Values.nats.enabled) .Values.nats.authUsers.enabled .Values.nats.authUsers.secret.create (not .Values.nats.authUsers.existingSecret) (gt (len .Values.nats.authUsers.clients) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wrapper.nats.authUsersSecretName" . }}
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: auth-users
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ include "wrapper.nats.authUsersIncludeKey" . }}: |
{{ include "wrapper.nats.authUsersJSON" . | trim | nindent 4 }}
{{- end }}
