apiVersion: v2
name: victoria-metrics-operator
description: VictoriaMetrics Operator — wrapper around the official Helm chart

type: application
version: 0.1.0
appVersion: "v0.73.1"

dependencies:
  - name: victoria-metrics-operator
    version: 0.66.2
    repository: https://victoriametrics.github.io/helm-charts
    condition: enabled

keywords:
  - victoriametrics
  - operator
  - monitoring
  - observability
  - gitops

maintainers:
  - name: DevOps Team
    email: devops@workquark.org

sources:
  - https://github.com/VictoriaMetrics/operator
  - https://github.com/VictoriaMetrics/helm-charts
