apiVersion: v2
name: cloudnative-pg
description: CloudNative-PG operator — wrapper around the official Helm chart

type: application
version: 0.2.0
appVersion: "1.29.0"

dependencies:
  - name: cloudnative-pg
    version: 0.28.0
    repository: https://cloudnative-pg.github.io/charts
    condition: enabled

keywords:
  - cloudnative-pg
  - postgresql
  - operator
  - gitops

maintainers:
  - name: DevOps Team
    email: devops@jrclabs.xyz

sources:
  - https://github.com/cloudnative-pg/cloudnative-pg
