image:
  repository: harbor.jrclabs.xyz/staypingo/staypingo-admin-api
  tag: v0.0.2
  pullPolicy: IfNotPresent

replicas: 1

containerPort: 8080
servicePort: 80

environment: prod

imagePullSecrets:
  - name: staypingo-admin-api-registry

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "200m"
    memory: 256Mi

externalSecrets:
  secretStore: vault-secretstore
  registryCredentialKey: harbor/staypingo-registry-credential

httproute:
  hostname: admin.staypingo.home.arpa
  path: /
  gatewayName: gateway
  gatewayNamespace: gateway-system
  gatewayListener: http
