apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alarmify-schedule-api-vars
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alarmify-schedule-api
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: alarmify
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/managed: "true"
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: alarmify-schedule-api-vars
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/name: alarmify-schedule-api
          app.kubernetes.io/component: credentials
          app.kubernetes.io/part-of: alarmify
          app.kubernetes.io/managed-by: Helm
        annotations:
          external-secrets.io/managed-by: external-secrets
  dataFrom:
    {{- range .Values.externalSecrets.appVarsKeys }}
    - extract:
        key: {{ . }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
