apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alarmify-schedule-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: alarmify
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alarmify-schedule-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: http
