#{{- if .Values.devCluster.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-cluster
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: dev-cluster
    app.kubernetes.io/component: cluster-secret
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/managed: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "{{ .Values.devCluster.externalSecrets.refreshInterval }}"
  secretStoreRef:
    name: "{{ .Values.devCluster.externalSecrets.secretStore }}"
    kind: ClusterSecretStore
  target:
    name: dev-cluster
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          cluster-name: "{{ .Values.devCluster.name }}"
          environment: dev
          app.kubernetes.io/name: dev-cluster
          app.kubernetes.io/component: cluster-secret
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/managed-by: Helm
          # ollama: "true"
          cilium: "true"
          # gateway-api-crds: "true"
          victoria-metrics: "true"
        annotations:
          external-secrets.io/managed-by: external-secrets
      data:
        server: "{{ .Values.devCluster.server }}"
        name: "{{ .Values.devCluster.name }}"
        config: '{"bearerToken":"{{`{{ .bearerToken }}`}}","tlsClientConfig":{"insecure":false,"caData":"{{`{{ .caData }}`}}"}}'
  data:
    - secretKey: bearerToken
      remoteRef:
        key: "{{ .Values.devCluster.externalSecrets.vaultPath }}"
        property: bearerToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: caData
      remoteRef:
        key: "{{ .Values.devCluster.externalSecrets.vaultPath }}"
        property: caData
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
#{{- end }}
