apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: staypingo-admin-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: Helm
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
