enabled: true

namespace:
  create: true
  name: gateway-system

gateways:
  internal:
    enabled: true
    name: gateway
    gatewayClassName: ""
    addressName: ""
    allowedRoutesFrom: All
    http:
      enabled: true
      port: 80
    https:
      enabled: false
      port: 443
      certificateRefs: []
  external:
    enabled: true
    name: gateway-external
    gatewayClassName: ""
    addressName: ""
    allowedRoutesFrom: All
    http:
      enabled: true
      port: 80
    https:
      enabled: false
      port: 443
      certificateRefs: []

healthCheckPolicies: []
